server:
  port: 8101
spring:
  application:
    name: config
  profiles:
    active: dev  #  开发配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/springcloudlynn/springcloudinactivity #配置git仓库地址
          search-paths: repo #  配置仓库的路径
          username: medoo-Ai
          password: Print1012
      label: master #  配置仓库的分支
# eureka
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/